# Generated by Django 2.1.2 on 2018-11-06 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0005_auto_20181104_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_subject',
        ),
        migrations.AddField(
            model_name='choice',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.Category'),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.Category'),
        ),
    ]
