# Generated by Django 2.1.2 on 2018-11-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0006_auto_20181106_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='category',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_given',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
