# Generated by Django 2.1.2 on 2018-11-10 00:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0007_auto_20181110_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2018, 11, 10, 0, 53, 51, 247688, tzinfo=utc)),
        ),
    ]
