# Generated by Django 2.1.2 on 2018-11-11 08:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0012_auto_20181111_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2018, 11, 11, 8, 36, 18, 335395, tzinfo=utc)),
        ),
    ]
