# Generated by Django 2.1.2 on 2018-11-22 22:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0018_auto_20181111_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2018, 11, 22, 22, 59, 3, 859334, tzinfo=utc)),
        ),
    ]
