# Generated by Django 2.1.2 on 2018-12-03 20:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0019_auto_20181122_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CitiesOfTheWorldTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, unique=True)),
                ('country', models.CharField(max_length=50, unique=True)),
                ('continent', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2018, 12, 3, 20, 16, 18, 146075, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='choices',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.Question'),
        ),
    ]
