# Generated by Django 2.1.2 on 2018-12-04 22:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0020_auto_20181203_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionGenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2018, 12, 4, 22, 18, 39, 291517, tzinfo=utc)),
        ),
    ]
