# Generated by Django 2.1.2 on 2018-12-04 22:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0022_auto_20181204_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2018, 12, 4, 22, 28, 43, 160554, tzinfo=utc)),
        ),
    ]
