# Generated by Django 2.1.2 on 2018-12-06 05:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0023_auto_20181204_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2018, 12, 6, 5, 25, 54, 519216, tzinfo=utc)),
        ),
    ]
